# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [91]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [18]:
A = np.arange(1, 16).reshape(3,5)

In [19]:
print("Matrix:")
print(A)
print("\nNumber of axes (ndim):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Data type (dtype):", A.dtype)

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Number of axes (ndim): 2
Shape: (3, 5)
Size: 15
Data type (dtype): int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [20]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [21]:
print(B - C )
print ()
print(B * C)
print ()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [22]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
E = np.exp(D)
print(E)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [41]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [42]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [43]:
# Specific index rows will be printed. In this case, the second row is printed, since indexing always starts from position zero.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [44]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [ ]:
# Use ndite for iterate element by element
for x in np.nditer(A):
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# Create 1D arry in 'a' variabled. contain number range 0 to 29
# reshape 'a' arry from 1D to 3D and ccopy result to varible 'b'. reshape((<block count>, <row count>, <element prt row (-1 = numpy distribute element equal on define row)>)

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [53]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [54]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [57]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
import numpy as np

def add_mult_matrices(A, B, operation):
    # Validate input types
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
        print("Both inputs must be numpy.ndarray")

    # Validate operation
    if operation not in ("add", "multiply"):
        print("Operation must be 'add' or 'multiply'")

    # Matrix addition
    if operation == "add":
        if A.shape != B.shape:
            print("For addition, matrices must have the same shape")
        return A + B

    # Matrix multiplication
    if operation == "multiply":
        if A.ndim != 2 or B.ndim != 2:
            print( "Matrix multiplication requires 2D arrays")
        if A.shape[1] != B.shape[0]:
            print( "For multiplication, number of columns in A " "must equal number of rows in B")
        return A @ B

In [87]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [88]:
add_mult_matrices(A, B, "add")

array([[ 6,  8],
       [10, 12]])

In [89]:
add_mult_matrices(A, B, "multiply")

array([[19, 22],
       [43, 50]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [122]:

## Upgift 10.1.1
##
##

import numpy as np

# Definiera vektorn x som radvektor
x = np.array([4, 3])  # 1D-array (radvektor)

# Gör om till kolonnvektor
x_col = x.reshape(-1, 1)  # 2x1



# Definiera vektorn x
x = np.array([4, 3])


print("Antal  dimentioner: 2D")


# 4. Multiplicera x med skalärer (5x, 3x, 4x-x, 8x)
five_x = 5 * x
print("5x =", five_x)

three_x = 3 * x
print("3x =", three_x)

print("5x + 3x =", five_x + three_x)

eight_x = 8 * x
print("8x =", eight_x)

four_x_minus_x = 4 * x - x
print("4x - x =", four_x_minus_x)
print("------------------\n")


# Transponering
x_col = x.reshape(-1, 1)   # gör om till kolonnvektor (2 rows x1 column) 
x_transpose = x_col.T      # transponera tillbaka till radvektor (1x2)

print("x som kolonnvektor:\n", x_col)
print("x transponerad:\n", x_transpose)
print("------------------\n")


print ("H -- Får inte except att funka, beräkning borde inte fugera ..?")
# matrisen måste dimensionerna vara samma.
try:
    x + x_col
except ValueError as e:
    print("Direkt addition ej definierad:", e)

print("------------------\n")


norm_x = np.linalg.norm(x)
print ("Beräkna normen: ||x|| =", norm_x)
print("------------------\n")



Antal  dimentioner: 2D
5x = [20 15]
3x = [12  9]
5x + 3x = [32 24]
8x = [32 24]
4x - x = [12  9]
------------------

x som kolonnvektor:
 [[4]
 [3]]
x transponerad:
 [[4 3]]
------------------

H -- Får inte except att funka, beräkning borde inte fugera ..?
------------------

Beräkna normen: ||x|| = 5.0
------------------



In [ ]:
## Upgift 10.1.2
import numpy as np

# Definiera vektorn x som radvektor
v = np.array([3, 7, 0, 11])

# Skriv ut vektorn
print("Vektorn v:", v)

# Beräkna dimensionen (antal komponenter)
dimension = v.shape[0]
print("Dimensionen av vektorn v:", dimension)
print("------------------\n")

two_v = 2 * v
print("2v =", two_v)
print("------------------\n")

print("5v + 2v =", (5*v) + two_v)
print("------------------\n")

print("4v + 2v =", (4*v) - two_v)
print("------------------\n")


v = v.reshape(-1, 1) 
print("v:\n", v)
print("Form på v:", v.shape)  # (4, 1)
# Transponera vektorn
vT = v.T
print("vT:\n", vT)
print("Form på vT:", vT.shape)  # (1, 4)
print("------------------\n")


norm_v = np.linalg.norm(v)
print ("Beräkna normen: ||v|| =", norm_v)
print("------------------\n")


Vektorn v: [ 3  7  0 11]
Dimensionen av vektorn v: 4
------------------

2v = [ 6 14  0 22]
------------------

5v + 2v = [21 49  0 77]
------------------

4v + 2v = [ 6 14  0 22]
------------------

v:
 [[ 3]
 [ 7]
 [ 0]
 [11]]
Form på v: (4, 1)
vT:
 [[ 3  7  0 11]]
Form på vT: (1, 4)
------------------

Beräkna normen: ||v|| = 13.379088160259652
------------------



In [126]:
## Upgift 10.1.3
import numpy as np

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])


norm_v1 = np.linalg.norm(v1)
print ("Beräkna normen: ||v1|| =", norm_v1)
print("------------------\n")

diff = v1 - v2
norm_diff = np.linalg.norm(diff)
print("||v1 - v2|| =", norm_diff)


Beräkna normen: ||v1|| = 7.14142842854285
------------------

||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [10]:

import numpy as np

print ("Formen Ax = b")
# Matris A
A = np.array([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 1],
    [7, 1, 5]
])

# Vektor b
b = np.array([7, 4, 11, 9])
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
##  input - har inte löst koden självs var tvungen att söka 

print("Lösningen x är:", x)


Formen Ax = b
Lösningen x är: [ 1.88969578  4.6033366  -1.75034347]


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [25]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)


[0 1 2 3]
[2 3]


In [26]:
print(v2.base is v1)

## Base return  'True' if there is a view and return 'None' it's a copy

True
